# Docker file for flask-based docker

FROM python:3.12

# Update python3, install pip3, netstat, virtualenv
ENV DEBIAN_FRONTEND teletype
RUN apt-get update && apt-get install -y apt-utils
RUN apt-get install -y python3-pip net-tools acl openssh-server nginx socat  && pip3 install --upgrade virtualenv

COPY ./ /TiledViz

RUN pip3 install --upgrade pip

RUN rm -rf /TiledViz/TVFiles/* /TiledViz/envDB

# create and run virtualenv
RUN sed -e 's/#GatewayPorts .*/GatewayPorts yes/' -i /etc/ssh/sshd_config; \
    virtualenv -p python3 flask_venv && \
    /bin/bash -c "source /flask_venv/bin/activate ; \
                  export LC_ALL=C.UTF-8 ; \
                  export LANG=C.UTF-8 ; \
		  pip3 install -r /TiledViz/TVWeb/requirements.txt ;\
		  pip3 cache purge ;"

ENV SERVER_NAME pc96
ENV DOMAIN mdls.fr
ENV SSLpublic /etc/letsencrypt/archive/mdls.fr/fullchain.pem
ENV SSLprivate /etc/letsencrypt/archive/mdls.fr/privkey.pem

# SMTP Configuration
ENV SMTP_SERVER smtp.mail.ovh.net
ENV SMTP_PORT 465
ENV SMTP_USE_SSL true
ENV SMTP_USE_TLS false
ENV SMTP_USERNAME pc218@mdls.fr
ENV FROM_EMAIL pc218@mdls.fr
# IMAP Configuration
ENV IMAP_SERVER imap.mail.ovh.net
ENV IMAP_PORT 993


HEALTHCHECK --interval=5m --timeout=10s --retries=1 CMD curl --fail https://pc96.mdls.fr/test || exit 1

#EXPOSE 5000

ENTRYPOINT ["/TiledViz/TVWeb/FlaskDocker/start_docker_web.sh"]

CMD ["localhost", "6431", "TiledViz", "tiledviz", "m_test/@03", "flaskhost", "1002", "1002", "m_smtp_p@sw0rd", "I-am-a-wonderful-unicorn"]
