name: Deploy Doxygen to GitHub Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Récupérer le code source
        uses: actions/checkout@v4

      - name: 2. Installer Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: 3. Générer la documentation
        run: doxygen Doxyfile

      - name: 4. Préparer le dossier HTML
        uses: actions/upload-pages-artifact@v3
        with:
          path: '@CMAKE_CURRENT_BINARY_DIR@/html'

      - name: 5. Déployer sur le site web
        id: deployment
        uses: actions/deploy-pages@v4
